### PR TITLE
Messed up xml decl

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
@ctsims in case sheel confirms this is real input

**Comment by dannyroberts** [comment]
@ctsims Sheel has confirmed this is real input...

I'm also planning (in a later PR) to send back a failure to parse flag to the phone as well when the this app can't parse it (and doesn't know what extra hack to add to parse it), since if we're seeing shit like this who knows what else could show up in these card scans

**Comment by ctsims** [comment]
QQ: Is this a widespread issue? Do we anticipate having to be able to
resolve it, or is it, like, "this indvidual's card was messed up"?

-Clayton

**Comment by dannyroberts** [comment]
@sheelio see @ctsims's question. 

I mean, it was a scan of an official health card issued by the government of india. I feel like we don't have much choice but to accommodate for their mistakes if we want this scanner to work on as many indian health cards as possible?

**Comment by dannyroberts** [comment]
(implemented `statusCode` for this purpose)

**Comment by sheelio** [comment]
@ctsims Yup, real scan.  

Want to use this "statusCode" value to eventually figure out the different permutations of scans that we have that we don't understand.

**Comment by dannyroberts** [comment]
Gonna just merge this myself since I'm the only dev on it; but @phillipm let me know if you have any comments on the code

**Pull request merged**
